from covidtracker import CovidTracker
cd = CovidTracker()
cd.load_counties()
cd.load_population()
cd.load_maskstats()
#df = cd.getperiodchange_state('New York', '2020-07-11', days=7, includepop=True)
#df = cd._imoortpopulation(df)
df=cd.getperiodchange('2020-09-15', days=14, includepop=True, includemaskuse=True)
df.sort_values('cases', ascending=False)
print(df)
